package api

import (
	"fmt"
	"net/http"

	"github.com/gorilla/handlers"
	"github.com/gorilla/mux"
	"github.com/joaquinleonarg/wdml-mtg/backend/api/routes/auth"
	"github.com/joaquinleonarg/wdml-mtg/backend/api/routes/boosterpacks"
	"github.com/joaquinleonarg/wdml-mtg/backend/api/routes/collection"
	"github.com/joaquinleonarg/wdml-mtg/backend/api/routes/deck"
	"github.com/joaquinleonarg/wdml-mtg/backend/api/routes/match"
	"github.com/joaquinleonarg/wdml-mtg/backend/api/routes/season"
	"github.com/joaquinleonarg/wdml-mtg/backend/api/routes/tournament"
	"github.com/joaquinleonarg/wdml-mtg/backend/api/routes/tournament_post"
	"github.com/joaquinleonarg/wdml-mtg/backend/config"

	_ "github.com/joaquinleonarg/wdml-mtg/backend/api/docs" // docs is generated by Swag CLI: swag init
	httpSwagger "github.com/swaggo/http-swagger/v2"
)

// @title Tolarian Archives API
// @version 1.1
// @description Private backend HTTP API for Tolarian Archives
// @contact.name Joaquin Leon
// @contact.email leonjoaquin77@gmail.com
// @host api.tolarianarchives.xyz
// @BasePath /v1

func StartServer() {
	router := mux.NewRouter().PathPrefix("/v1").Subrouter()

	router.PathPrefix("/swagger/").Handler(httpSwagger.Handler(
		httpSwagger.URL("/v1/swagger/doc.json"), //The url pointing to API definition
		httpSwagger.DeepLinking(true),
		httpSwagger.DocExpansion("none"),
		httpSwagger.DomID("swagger-ui"),
	)).Methods(http.MethodGet)

	authRouter := router.NewRoute().Subrouter()
	auth.RegisterEndpoints(authRouter)

	router.Use(auth.AuthMiddleware)
	tournament.RegisterEndpoints(router)
	boosterpacks.RegisterEndpoints(router)
	collection.RegisterEndpoints(router)
	deck.RegisterEndpoints(router)
	season.RegisterEndpoints(router)
	match.RegisterEndpoints(router)
	tournament_post.RegisterEndpoints(router)

	originsOk := handlers.AllowedOrigins([]string{config.Config.CorsOrigin})
	credentialsOk := handlers.AllowCredentials()
	headersOk := handlers.AllowedHeaders([]string{"X-Requested-With", "*"})
	methodsOk := handlers.AllowedMethods([]string{"GET", "HEAD", "POST", "PUT", "OPTIONS"})

	router.Walk(func(route *mux.Route, router *mux.Router, ancestors []*mux.Route) error {
		tpl, _ := route.GetPathTemplate()
		met, _ := route.GetMethods()
		fmt.Println(tpl, met)
		return nil
	})

	http.ListenAndServe(fmt.Sprintf(":%v", config.Config.ApiPort), handlers.CORS(originsOk, credentialsOk, headersOk, methodsOk)(router))
}
